name: GeumuDiscordSystem
version: '1.0-SNAPSHOT'
main: gaya.pe.kr.plugin.GeumuDiscordSystem
authors: [GEUMU]
description: Geumu Discord & Minecraft Question System


commands:
  test123:
  질문:
  답변:
  인증: