package gaya.pe.kr.util.option.type;

public enum OptionType {

    CONFIG,
    WAITING_ANSWER_LIST_GUI,
    ANSWER_RANKING_GUI,
    COMMONLY_USED_BUTTON_GUI,
    PLAYER_ANSWER_LIST_GUI,
    PLAYER_QUESTION_LIST_GUI,
    QUESTION_RANKING_GUI,
    ANSWER_PATTEN


}
