package gaya.pe.kr.velocity.minecraft.parser;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;

/**
 * Message Type 이지 PlaceHolder 와의 연관성이 없음
 */
public enum MessageType {

    TITLE_PLAYER_QUESTION_LIST,
    TITLE_PLAYER_ANSWER_LIST,
    TITLE_ANSWER_LIST,

    INVALID_PLAYERNAME,
    INVALID_ANSWER_NUMBER,
    INVALID_AUTHENTICATION_CODE,
    QUESTION_HELP_SUCCESS_USER,
    QUESTION_HELP_SUCCESS_STAFF,
    QUESTION_HELP_SUCCESS_ADMIN,
    QUESTION_SUCCESS_BROADCAST, // %playername% : %question_content%
    QUESTION_FAIL_QUESTION_TOO_SHORT, // %question_min_length%
    QUESTION_FAIL_QUESTION_TOO_LONG, // %question_max_length%
    QUESTION_FAIL_QUESTION_COOLDOWN, // %question_cooldown%

    ANSWER_SEND_SUCCESS_IF_QUESTIONER_ONLINE_BROADCAST,
    ANSWER_SEND_SUCCESS_IF_QUESTIONER_ONLINE,
    ANSWER_SEND_SUCCESS_IF_QUESTIONER_OFFLINE,

    TITLE_ANSWER_RECEIVE_SUCCESS_IF_QUESTIONER_ONLINE,
    SUB_TITLE_ANSWER_RECEIVE_SUCCESS_IF_QUESTIONER_ONLINE,

    ANSWER_RECEIVE_SUCCESS_IF_QUESTIONER_OFFLINE_AND_JOIN_AFTER,

    ANSWER_RECEIVE_SUCCESS_IF_QUESTIONER_OFFLINE_AND_JOIN_AFTER_TITLE,
    ANSWER_RECEIVE_SUCCESS_IF_QUESTIONER_OFFLINE_AND_JOIN_AFTER_SUBTITLE,

    ANSWER_SEND_FAIL_ANSWER_COOLDOWN,
    ANSWER_SEND_FAIL_CAN_NOT_SELF_ANSWER,

    ANSWER_SEND_FAIL_ALREADY_ANSWERED_RECENT_QUESTION_AND_NO_REMAIN_OLD_QUESTION,
    ANSWER_SEND_FAIL_ALREADY_ANSWERED_RECENT_QUESTION_AND_REMAIN_OLD_QUESTION,
    ANSWER_SEND_FAIL_ALREADY_ANSWERED_RECENT_QUESTION_AND_REMAIN_OLD_QUESTION_HOVER_MESSAGE,

    ANSWER_SEND_FAIL_NOT_EXIST_RECENT_QUESTION_AND_NO_REMAIN_OLD_QUESTION,
    ANSWER_SEND_FAIL_NOT_EXIST_RECENT_QUESTION_AND_REMAIN_OLD_QUESTION,
    ANSWER_SEND_FAIL_NOT_EXIST_RECENT_QUESTION_AND_REMAIN_OLD_QUESTION_HOVER_MESSAGE,

    QUESTION_NUMBER_ANSWER_SEND_SUCCESS_IF_QUESTIONER_ONLINE,
    QUESTION_NUMBER_ANSWER_SEND_SUCCESS_IF_QUESTIONER_OFFLINE,

    QUESTION_NUMBER_ANSWER_RECEIVE_SUCCESS_IF_QUESTIONER_ONLINE,

    QUESTION_NUMBER_ANSWER_RECEIVE_SUCCESS_IF_QUESTIONER_ONLINE_TITLE,
    QUESTION_NUMBER_ANSWER_RECEIVE_SUCCESS_IF_QUESTIONER_ONLINE_SUBTITLE,

    QUESTION_NUMBER_ANSWER_RECEIVE_SUCCESS_IF_QUESTIONER_OFFLINE_AND_JOIN_AFTER,
    QUESTION_NUMBER_ANSWER_RECEIVE_SUCCESS_IF_QUESTIONER_OFFLINE_AND_JOIN_AFTER_TITLE,
    QUESTION_NUMBER_ANSWER_RECEIVE_SUCCESS_IF_QUESTIONER_OFFLINE_AND_JOIN_AFTER_SUBTITLE,

    QUESTION_NUMBER_ANSWER_SEND_FAIL_CAN_NOT_SELF_ANSWER,
    QUESTION_NUMBER_ANSWER_SEND_FAIL_ANSWER_COOLDOWN,
    AUTHENTICATION_FAIL_AUTHENTICATION_CODE_DOES_NOT_MATCH,

    AUTHENTICATION_CODE_GENERATION_SUCCESS,
    AUTHENTICATION_CODE_GENERATION_FAIL_AUTHENTICATION_CODE_ALREADY_GENERATED,
    AUTHENTICATION_CODE_GENERATION_FAIL_NOT_EXIST_MINECRAFT_ACCOUNT,

    AUTHENTICATION_CODE_EXPIRED,

    DISCORD_AUTHENTICATION_CHANNEL_HELP_MESSAGE,
    DISCORD_QUESTION_CHANNEL_PREFIX_HELP_MESSAGE,
    REMOVEQ_SUCCESS_REMOVE_PERSON,
    REMOVEQ_SUCCESS_HAS_BEEN_REMOVED_PERSON,
    REMOVEQ_FAIL_NOT_EXIST,

    REMOVEA_SUCCESS_REMOVE_PERSON,
    REMOVEA_SUCCESS_HAS_BEEN_REMOVED_PERSON,
    REMOVEA_FAIL_NOT_EXIST,

    REMOVE_REWARD_SUCCESS,

    RELOAD_SUCCESS,

    ANSWER_PLAYERNAME_PLACEHOLDER_AUTO_ANSWER,
    REWARD_PAYMENT_SUCCESS_BROADCAST;

    List<String> messages;

    public void setMessages(List<String> messages) {
        this.messages = messages;
    }

    public void setMessage(String message) {
        this.messages = Collections.singletonList(message);
    }

    public List<String> getMessages() {
        return new ArrayList<String>(messages);
    }
}
